language: swift
osx_image: xcode11
sudo: required

addons:
  homebrew:
    taps:
      - adoptopenjdk/openjdk
      - bow-swift/nef
    packages:
      - nef
    casks:
      - adoptopenjdk/openjdk/adoptopenjdk8

env:
  global:
    - PROJECT="BowOpenAPI.xcodeproj"
    - JOB="XCODE"
    - DEST="platform=macOS,arch=x86_64"
    - SCHEME="Markup"
    - SDK="macosx"
    - ACTION="test"

jobs:
  include:
    - stage: test
      name: "Tests"
      install:
        - set -o pipefail
        - export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
        - export PATH=${JAVA_HOME}/bin:$PATH
        - java -version
      before_script:
        - set -o pipefail
        - brew install swagger-codegen
        - xcodebuild build -project "$PROJECT" -scheme "Fixtures" -destination "$DEST" | xcpretty -c
      script:
        - set -o pipefail
        - xcodebuild test -project "$PROJECT" -scheme "Tests" -destination "$DEST" | xcpretty -c
    - stage: verify documentation
      before_install:
        - gem update --system
        - gem install cocoapods
      script:
        - nef compile Documentation.app
    - stage: deploy microsite
      if: branch = master AND type != pull_request
      install:
        - gem install bundler --force
        - bundle install --gemfile docs/Gemfile --path vendor/bundle
      script:
        - nef jekyll --project Documentation.app --output docs --main-page Documentation.app/Jekyll/Home.md
        - BUNDLE_GEMFILE=./docs/Gemfile bundle exec jekyll build -s docs -d gen-docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: gen-docs
        target-branch: gh-pages
        on:
          all_branches: true
