language:
    - swift
    - java
osx_image: xcode11
jdk: openjdk8

addons:
  homebrew:
    packages: swagger-codegen
    
env:
  global:
    - ROOT="Bow OpenAPI"
    - PROJECT="Bow OpenAPI.xcodeproj"
    - JOB="XCODE"
    - DEST="platform=macOS,arch=x86_64"

jobs:
  include:
    - stage: test
      name: "Tests"
      before_install:
        - set -o pipefail
        - java -version
        - cd "$ROOT"
        - xcodebuild build -project "$PROJECT" -scheme "Fixtures" -destination "$DEST" | xcpretty -c
      script:
        - set -o pipefail
        - xcodebuild test -project "$PROJECT" -scheme "Tests" -destination "$DEST" | xcpretty -c
