language: swift
osx_image: xcode11
sudo: required

addons:
  homebrew:
    casks: homebrew/cask-versions/adoptopenjdk8

env:
  global:
    - PROJECT="BowOpenAPI.xcodeproj"
    - JOB="XCODE"
    - DEST="platform=macOS,arch=x86_64"

jobs:
  include:
    - stage: test
      name: "Tests"
      install:
        - set -o pipefail
        - export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
        - export PATH=${JAVA_HOME}/bin:$PATH
        - java -version
      before_script:
        - set -o pipefail
        - brew install swagger-codegen
        - xcodebuild build -project "$PROJECT" -scheme "Fixtures" -destination "$DEST" | xcpretty -c
      script:
        - set -o pipefail
        - xcodebuild test -project "$PROJECT" -scheme "Tests" -destination "$DEST" | xcpretty -c
