//
//  Pet.swift
//
//  Generated by bow-openapi
//  Copyright © 2019 Bow Authors. All rights reserved.
//

import Foundation


public struct Pet: Codable {

    public var name: String

    public init(name: String) {
        self.name = name
    }
}
