#if !canImport(ObjectiveC)
import XCTest

extension APIClientDocumentationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIClientDocumentationTests = [
        ("testModelDocumented", testModelDocumented),
        ("testRequestDocumented", testRequestDocumented),
    ]
}

extension APIClientGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIClientGeneratorTests = [
        ("testApiClientGenerated_JSONAndYAML_WithSameSpecification_GenerateSameAPIClient", testApiClientGenerated_JSONAndYAML_WithSameSpecification_GenerateSameAPIClient),
        ("testApiClientGenerated_JSONSchema", testApiClientGenerated_JSONSchema),
        ("testApiClientGenerated_OpenAPIAndJSONSchema_WithSameSpecification_GenerateSameAPIClient", testApiClientGenerated_OpenAPIAndJSONSchema_WithSameSpecification_GenerateSameAPIClient),
        ("testApiClientGenerated_OpenAPISchema", testApiClientGenerated_OpenAPISchema),
        ("testApiClientGenerated_SwaggerSchema", testApiClientGenerated_SwaggerSchema),
        ("testApiClientGenerated_YAMLSchema", testApiClientGenerated_YAMLSchema),
        ("testDefinedTags_GenerateTagAPI", testDefinedTags_GenerateTagAPI),
        ("testNoDefinedTags_GenerateDefaultAPI", testNoDefinedTags_GenerateDefaultAPI),
    ]
}

extension APIClientHttpOperationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIClientHttpOperationTests = [
        ("testNoDefinedOperationId_OperationUsingEndpointNaming", testNoDefinedOperationId_OperationUsingEndpointNaming),
        ("testRequestDELETE", testRequestDELETE),
        ("testRequestGET", testRequestGET),
        ("testRequestPOST", testRequestPOST),
        ("testRequestPUT", testRequestPUT),
    ]
}

extension APIClientModelsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIClientModelsTests = [
        ("testModelDefinition_BuildPetModel", testModelDefinition_BuildPetModel),
        ("testModelDefinitionOptional_BuildModelWithOptionals", testModelDefinitionOptional_BuildModelWithOptionals),
        ("testModelInlineInRequest", testModelInlineInRequest),
        ("testModelInResponse_APIClient", testModelInResponse_APIClient),
        ("testModelInResponse_Model", testModelInResponse_Model),
        ("testModelWithReferences", testModelWithReferences),
        ("testRequestWithPetReference_BuildPetModel", testRequestWithPetReference_BuildPetModel),
    ]
}

extension APIClientParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIClientParametersTests = [
        ("testRequestWithBodyParam_BuildRequestPath", testRequestWithBodyParam_BuildRequestPath),
        ("testRequestWithBodyParamOptional_BuildRequestPath", testRequestWithBodyParamOptional_BuildRequestPath),
        ("testRequestWithContentType_ApplicationJson", testRequestWithContentType_ApplicationJson),
        ("testRequestWithContentType_WWWFormURLEncoded", testRequestWithContentType_WWWFormURLEncoded),
        ("testRequestWithHeaderParam_GenerateHelperMethod", testRequestWithHeaderParam_GenerateHelperMethod),
        ("testRequestWithHeaderParamOptional_GenerateHelperMethodNoOptional", testRequestWithHeaderParamOptional_GenerateHelperMethodNoOptional),
        ("testRequestWithPathParam_BuildRequestPath", testRequestWithPathParam_BuildRequestPath),
        ("testRequestWithPathParamOptional_BuildRequestPathNoOptional", testRequestWithPathParamOptional_BuildRequestPathNoOptional),
        ("testRequestWithQueryParam_URLComponentsAndQueryItems", testRequestWithQueryParam_URLComponentsAndQueryItems),
        ("testRequestWithQueryParamOptional_URLComponentsAndQueryItems", testRequestWithQueryParamOptional_URLComponentsAndQueryItems),
    ]
}

extension APIClientSendTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIClientSendTests = [
        ("testAPIClient_EmptyJSONResponse_ReturnNoResponse", testAPIClient_EmptyJSONResponse_ReturnNoResponse),
        ("testAPIClient_EmptyStringResponse_ReturnNoResponse", testAPIClient_EmptyStringResponse_ReturnNoResponse),
        ("testAPIClient_InvalidResponseWithCode400_ReturnBadRequest", testAPIClient_InvalidResponseWithCode400_ReturnBadRequest),
        ("testAPIClient_InvalidResponseWithCode403_ReturnForbiddenError", testAPIClient_InvalidResponseWithCode403_ReturnForbiddenError),
        ("testAPIClient_InvalidResponseWithCode404_ReturnNotFoundError", testAPIClient_InvalidResponseWithCode404_ReturnNotFoundError),
        ("testAPIClient_InvalidResponseWithCode500_ReturnServerError", testAPIClient_InvalidResponseWithCode500_ReturnServerError),
        ("testAPIClient_InvalidResponseWithCode503_ReturnServiceUnavailable", testAPIClient_InvalidResponseWithCode503_ReturnServiceUnavailable),
        ("testAPIClient_InvalidResponseWithUnknownCode_ReturnUnknownError", testAPIClient_InvalidResponseWithUnknownCode_ReturnUnknownError),
        ("testAPIClient_RoutingStubs", testAPIClient_RoutingStubs),
        ("testAPIClient_StackingResponses", testAPIClient_StackingResponses),
        ("testAPIClient_ValidRequestAndData_ShouldReceiveValidData", testAPIClient_ValidRequestAndData_ShouldReceiveValidData),
        ("testAPIClient_ValidRequestAndInvalidData_ReturnError", testAPIClient_ValidRequestAndInvalidData_ReturnError),
        ("testAPIClient_ValidRequestAndInvalidDecoder_ReturnParsingError", testAPIClient_ValidRequestAndInvalidDecoder_ReturnParsingError),
        ("testAPIClient_ValidRequestWithWrongDecoder_ReturnParsingError", testAPIClient_ValidRequestWithWrongDecoder_ReturnParsingError),
    ]
}

extension APIConfigTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIConfigTests = [
        ("testCopy", testCopy),
        ("testCopyHeaders", testCopyHeaders),
        ("testHeaders", testHeaders),
        ("testHeaders_Idempotent", testHeaders_Idempotent),
        ("testHeaders_Identity", testHeaders_Identity),
    ]
}

extension APIHelperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIHelperTests = [
        ("testQueryItems", testQueryItems),
    ]
}

extension GeneratorAPIClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeneratorAPIClientTests = [
        ("testBow_CreateDefaultStructure", testBow_CreateDefaultStructure),
        ("testBow_FileSystemFails_ReturnError", testBow_FileSystemFails_ReturnError),
        ("testBow_GeneratorAndFileSystemSuccess_ReturnSuccess", testBow_GeneratorAndFileSystemSuccess_ReturnSuccess),
        ("testBow_GeneratorFails_ReturnError", testBow_GeneratorFails_ReturnError),
        ("testBow_GeneratorIsInvoked", testBow_GeneratorIsInvoked),
        ("testCreateStructure", testCreateStructure),
        ("testCreateSwiftPackage", testCreateSwiftPackage),
    ]
}

extension GeneratorSwaggerClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeneratorSwaggerClientTests = [
        ("testFixSignatureParameters_WhenNeedFix_ReturnValidSignature", testFixSignatureParameters_WhenNeedFix_ReturnValidSignature),
        ("testFixSignatureParameters_WhenNotNeedFix_ReturnValidSignature", testFixSignatureParameters_WhenNotNeedFix_ReturnValidSignature),
        ("testRemoveHeaderSection_IsInvalid_ReturnSameFile", testRemoveHeaderSection_IsInvalid_ReturnSameFile),
        ("testRemoveHeaderSection_ReturnFileUpdated", testRemoveHeaderSection_ReturnFileUpdated),
        ("testRemoveHeaderSection_WithExtraContent_ReturnFileUpdated", testRemoveHeaderSection_WithExtraContent_ReturnFileUpdated),
        ("testRemoveHeaderSection_WithoutContent_ReturnSameFile", testRemoveHeaderSection_WithoutContent_ReturnSameFile),
        ("testRenderHelpersForHeaders_DifferentsHeaders_RenderMultiplesHelpers", testRenderHelpersForHeaders_DifferentsHeaders_RenderMultiplesHelpers),
        ("testRenderHelpersForHeaders_MultiplesSameHeaders_RenderOnlyHelper", testRenderHelpersForHeaders_MultiplesSameHeaders_RenderOnlyHelper),
        ("testRenderHelpersForHeaders_MultiplesSameHeadersInDifferentsFiles_RenderOnlyHelper", testRenderHelpersForHeaders_MultiplesSameHeadersInDifferentsFiles_RenderOnlyHelper),
        ("testRenderHelpersForHeaders_ValidHeader_RenderHelper", testRenderHelpersForHeaders_ValidHeader_RenderHelper),
    ]
}

extension PackageGeneratedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageGeneratedTests = [
        ("testBuildProjectWithSwiftPackage", testBuildProjectWithSwiftPackage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
//        testCase(APIClientDocumentationTests.__allTests__APIClientDocumentationTests),
//        testCase(APIClientGeneratorTests.__allTests__APIClientGeneratorTests),
//        testCase(APIClientHttpOperationTests.__allTests__APIClientHttpOperationTests),
//        testCase(APIClientModelsTests.__allTests__APIClientModelsTests),
//        testCase(APIClientParametersTests.__allTests__APIClientParametersTests),
        testCase(APIClientSendTests.__allTests__APIClientSendTests),
        testCase(APIConfigTests.__allTests__APIConfigTests),
        testCase(APIHelperTests.__allTests__APIHelperTests),
        testCase(GeneratorAPIClientTests.__allTests__GeneratorAPIClientTests),
        testCase(GeneratorSwaggerClientTests.__allTests__GeneratorSwaggerClientTests),
//        testCase(PackageGeneratedTests.__allTests__PackageGeneratedTests),
    ]
}
#endif
