//
//  RequestDocAPI.swift
//
//  Generated by bow-openapi
//  Copyright © 2021 Bow Authors. All rights reserved.
//

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Bow
import BowEffects

/// `RequestDocAPI` provider
public extension API {
    static var `requestDoc`: RequestDocAPI {
        return RequestDocAPIClient()
    }
}


/// Protocol to define networking operations in `requestDoc`
public protocol RequestDocAPI {
    func _findPetsByStatus(status: Object?) -> EnvIO<API.Config, API.HTTPError, NoResponse>
}

extension RequestDocAPI {

    /**
     Finds Pets by status

     - Parameter status: (query) Status values that need to be considered for filter (optional)
     - Returns: An `EnvIO` to perform IO operations that produce errors of type `HTTPError` and values of type `Void`, having access to an immutable environment of type `API.Config`.
     */
    public func findPetsByStatus(status: Object? = nil) -> EnvIO<API.Config, API.HTTPError, NoResponse> {
        _findPetsByStatus(status: status)
    }
}


/// An HTTP client to perform networking operations related to `requestDoc`
class RequestDocAPIClient: RequestDocAPI {

    func _findPetsByStatus(status: Object?) -> EnvIO<API.Config, API.HTTPError, NoResponse> {
        return EnvIO { apiConfig in
            // build request path
            let resourcePath = "/pet/findByStatus"
            let path = apiConfig.basePath + resourcePath
            
            // make parameters
            let parameters: [String: Any]? = nil
            var components = URLComponents(string: path)
            components?.queryItems = [
                        "status": status
            ].toQueryItems
            
            // request configuration
            guard let url = components?.url ?? URL(string: path) else {
                let data = "RequestDocAPI.findPetsByStatus.URL".data(using: .utf8)!
                return IO.raiseError(.malformedURL(response: URLResponse.empty, data: data))
            }

            var request = URLRequest(url: url)
            request.httpMethod = "GET"
            request.addHeaders(apiConfig.headers)
            request.setParameters(parameters)
            
            // launch request
            return API.send(request: request, session: apiConfig.session, decoder: apiConfig.decoder)
        }
    }
}

