//
//  PetAPI.swift
//
//  Generated by bow-openapi
//  Copyright © 2020 Bow Authors. All rights reserved.
//

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Bow
import BowEffects

/// `PetAPI` provider
public extension API {
    static var `pet`: PetAPI {
        return PetAPIClient()
    }
}


/// Protocol to define networking operations in `pet`
public protocol PetAPI {
    func _getPet() -> EnvIO<API.Config, API.HTTPError, NoResponse>
}

extension PetAPI {

    /**
     Info for a specific pet

     - Returns: An `EnvIO` to perform IO operations that produce errors of type `HTTPError` and values of type `Void`, having access to an immutable environment of type `API.Config`.
     */
    public func getPet() -> EnvIO<API.Config, API.HTTPError, NoResponse> {
        _getPet()
    }
}


/// An HTTP client to perform networking operations related to `pet`
class PetAPIClient: PetAPI {

    func _getPet() -> EnvIO<API.Config, API.HTTPError, NoResponse> {
        return EnvIO { apiConfig in
            // build request path
            let resourcePath = "/pet"
            let path = apiConfig.basePath + resourcePath
            
            // make parameters
            
            let components = URLComponents(string: path)
            
            // request configuration
            guard let url = components?.url ?? URL(string: path) else {
                let data = "PetAPI.getPet.URL".data(using: .utf8)!
                return IO.raiseError(.malformedURL(response: URLResponse.empty, data: data))
            }

            var request = URLRequest(url: url)
            request.httpMethod = "GET"
            request.addHeaders(apiConfig.headers)
            
            // launch request
            return API.send(request: request, session: apiConfig.session, decoder: apiConfig.decoder)
        }
    }
}

