//
//  APIs.swift
//
//  Generated by bow-openapi
//  Copyright © 2019 Bow Authors. All rights reserved.
//

import Foundation

public class API {}


/// Helpers for update the headers in `API.Config`
extension API.Config {

    func append(headers: [String: String]) -> API.Config {
        self.copy(headers: self.headers.combine(headers))
    }
    
    func append(contentType: API.ContentType) -> API.Config {
        self.copy(headers: self.headers.combine(contentType.headers))
    }
    
    func appendHeader(value: String, forKey key: String) -> API.Config {
        self.copy(headers: self.headers.combine([key: value]))
    }
}


extension API.Config {

    func appendHeader(petIdTesting: Int) -> API.Config {
        self.copy(headers: self.headers.combine(["pet-Id-Testing": petIdTesting]))
    }
}